# Generated by Django 4.0.2 on 2022-06-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
