# Generated by Django 4.0.4 on 2022-05-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_marca_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='precio',
            field=models.IntegerField(default='0', max_length=7, verbose_name='Precio'),
        ),
    ]
