# Generated by Django 4.0.4 on 2022-05-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_marca_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='precio',
            field=models.IntegerField(default='0', verbose_name='Precio'),
        ),
    ]
