# Generated by Django 4.0.2 on 2022-06-08 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_marca_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='precio',
            field=models.FloatField(default='100', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Precio $'),
        ),
    ]
