# Generated by Django 4.0.2 on 2022-07-28 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activa'), ('Finalizada', 'Finalizada')], max_length=11, verbose_name='Estado')),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.usuario', verbose_name='Usuario')),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.vehículo', verbose_name='Vehículo')),
            ],
        ),
    ]
