# Generated by Django 4.0.2 on 2022-08-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activa'), ('Finalizada', 'Finalizada')], default='Activo', max_length=11, verbose_name='Estado')),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.usuario', verbose_name='Usuario')),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.vehículo', verbose_name='Vehículo')),
            ],
        ),
        migrations.CreateModel(
            name='detalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0.0)),
                ('cantidad', models.IntegerField(default=0.0)),
                ('factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.factura', verbose_name='Factura')),
                ('insumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.insumo', verbose_name='Insumo')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio', verbose_name='servicio')),
            ],
        ),
    ]
