# Generated by Django 4.0.2 on 2022-06-15 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Anulada', 'Anulada')], default='Activo', max_length=10, verbose_name='estado')),
                ('vehículo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Placa', to='registro.vehículo')),
            ],
        ),
    ]
