# Generated by Django 4.0.2 on 2022-08-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='total',
            field=models.IntegerField(blank=True, default=0.0),
        ),
    ]
