# Generated by Django 4.0.2 on 2022-07-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='cantidad',
            field=models.IntegerField(default=0.0, max_length=7),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.factura', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.insumo', verbose_name='Insumo'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio', verbose_name='servicio'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='total',
            field=models.IntegerField(default=0.0, max_length=7),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activa'), ('Finalizada', 'Finalizada')], default='Activo', max_length=11, verbose_name='Estado'),
        ),
    ]
