# Generated by Django 4.0.2 on 2022-06-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_factura_agregar_insumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='agregar_insumo',
        ),
    ]
