# Generated by Django 4.0.2 on 2022-08-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículo',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
    ]
