# Generated by Django 4.0.2 on 2022-06-21 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehículo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.vehículo'),
        ),
    ]
